INSERT INTO CUSTOMER (NAME, AGE, ADDRESS, ACCOUNT_OPENING_DATE) values ('Lep', 23, 'Manda', '2020-11-05');
INSERT INTO CUSTOMER (NAME, AGE, ADDRESS, ACCOUNT_OPENING_DATE) values ('Hi', 15, 'Manila', '2020-11-03');
INSERT INTO CUSTOMER (NAME, AGE, ADDRESS, ACCOUNT_OPENING_DATE) values ('Hello', 16, 'HK', '2020-11-01');
INSERT INTO CUSTOMER (NAME, AGE, ADDRESS, ACCOUNT_OPENING_DATE) values ('Rold', 17, 'Cebu', '2020-11-02');
INSERT INTO CUSTOMER (NAME, AGE, ADDRESS, ACCOUNT_OPENING_DATE) values ('Nathan', 23, 'Dyan', '2020-11-05');
INSERT INTO CUSTOMER (NAME, AGE, ADDRESS, ACCOUNT_OPENING_DATE) values ('Tapos', 14, 'Doon', '2020-11-05');

